host = localhost
port = 6600
music-dir = /srv/media/music/
scale = 200
text-topic = MPD Notification

# Clean normal notifications
text-play  = Playing: %t\nArtist: %a\nAlbum: %A
text-pause = Paused: %t\nArtist: %a\nAlbum: %A
text-stop  = Stopped playback

timeout = 20
