add_newline = false

format = """$username@$hostname
$directory
$character"""
right_format = """
$cmd_duration
"""

[custom.cpu]
command = "top -bn1 | grep 'Cpu(s)' | awk '{print int(100 - $8)\"%\"}'"
when = "true"
format = "[󰻠 $output]($style)"
style = "bold cyan"

[custom.ram]
command = "free -h | awk '/Mem:/ {print $3\"/\"$2}'"
when = "true"
format = "[󰍛 $output]($style) "
style = "#34eb92"

[custom.uptime]
command = "uptime -p | sed 's/up //'"
when = "true"
format = "[$output]($style) "

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%A, %d %B %Y | %-I:%M:%S %p"
style = "#bold white"

[cmd_duration]
min_time = 0
disabled = false
format = "took [$duration](#ff8800)"
show_milliseconds = true
show_notifications = true
min_time_to_notify = 45000

[localip]
ssh_only = false
format = '[$localipv4](#ff0000) '
disabled = false

[username]
show_always = true
format = "[$user]($style)"
style_user = "red"

[hostname]
ssh_only = false
format = "$hostname"
style = "blue"

[directory]
truncation_length = 0
truncate_to_repo = false
style = "#0ff000"
[character]
success_symbol = "[⟩](#88ff00)"
error_symbol = "[⟩](#ff0000)"
vicmd_symbol = "[⟩](bold purple)"


