# BACKGROUND
background {
    monitor =
    path = /home/Gnana/Pictures/Bhairavi.jpg
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 1.0
    crossfade_time = 2
}

# GENERAL
general {
    no_fade_in = true
    grace = 5
    disable_loading_bar = false
    ignore_empty_input = true
}


# INPUT FIELD
input-field {
    monitor =
    size = 350, 55
    rounding = 0
    outline_thickness = 1
    dots_size = 0.3 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgba(30, 30, 30, 0.2)
    font_color = rgb(199, 199, 199)
    check_color = rgba(255, 0, 0, 0.4)
    fail_color = rgba(204, 34, 34, 1.0)
    fade_on_empty = false
    font_family = IosevkaSS18
    font_size = 40
    placeholder_text = |Password| $FAIL $ATTEMPTS
    hide_input = false
    position = 970, 400
    dots_rounding = 0
    halign = center
    valign = center

}


# Date
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgb(ffffff)
  font_size = 22
  font_family = IosevkaSS18
  position = 960, 500
  halign = center
  valign = center
}
# Time
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%-I:%M:%S%p")"
  color = rgb(ffffff)
  font_size = 60
  font_family = IosevkaSS18
  position = 950, 600
  halign = center
  valign = center
}
