# BACKGROUND
background {
    monitor =
    path = /home/Gnana/Pictures/Bhairavi.jpg
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 1.0
    crossfade_time = 2
}

# GENERAL
general {
    no_fade_in = true
    grace = 5
    disable_loading_bar = false
    ignore_empty_input = true
}


# INPUT FIELD
input-field {
    monitor =
    size = 350, 55
    rounding = 10
    outline_thickness = 3
    dots_size = 0.3 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgba(0, 0, 0, 1)
    font_color = rgb(94, 255, 0)
    check_color = rgba(255, 0, 60, 1.0)
    fail_color = rgba(204, 34, 34, 1.0)
    fade_on_empty = false
    font_family = Iosevka
    font_size = 40
    placeholder_text = |...ENTER.PASSWORD...|
    hide_input = false
    position = 30, -700
    dots_rounding = 1
    halign = center
    valign = center
}
